// <auto-generated />
using System;
using CleanApp.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CleanApp.Persistence.Migrations
{
    [DbContext(typeof(CleanAppDbContext))]
    [Migration("20190408001407_AddFluentAPIForAddressAndClient")]
    partial class AddFluentAPIForAddressAndClient
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CleanApp.Domain.Entities.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("AddressID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City")
                        .HasMaxLength(50);

                    b.Property<string>("Country")
                        .HasMaxLength(100);

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(10);

                    b.Property<string>("ProvinceState")
                        .HasMaxLength(200);

                    b.Property<string>("Street")
                        .HasMaxLength(200);

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("CleanApp.Domain.Entities.BuyOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("CreatedDate");

                    b.Property<DateTime>("PaymentDate");

                    b.Property<DateTime>("ShippingDate");

                    b.Property<decimal>("ShippingPrice");

                    b.Property<DateTime?>("UpdatedDate");

                    b.HasKey("Id");

                    b.ToTable("BuyOrders");
                });

            modelBuilder.Entity("CleanApp.Domain.Entities.BuyOrderDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BuyOrderId");

                    b.Property<int>("MascotId");

                    b.Property<short>("Quantity");

                    b.Property<decimal>("UnitPrice");

                    b.HasKey("Id");

                    b.HasIndex("BuyOrderId");

                    b.HasIndex("MascotId");

                    b.ToTable("BuyOrderDetails");
                });

            modelBuilder.Entity("CleanApp.Domain.Entities.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ClientID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AddressId")
                        .HasColumnName("AddressID");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("LastName")
                        .HasMaxLength(100);

                    b.Property<string>("Messenger")
                        .HasMaxLength(50);

                    b.Property<string>("Phone")
                        .HasMaxLength(20);

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("CleanApp.Domain.Entities.Make", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AddressId");

                    b.Property<string>("Code");

                    b.Property<DateTime?>("CreatedDate");

                    b.Property<string>("Email");

                    b.Property<string>("Name");

                    b.Property<string>("Phone");

                    b.Property<DateTime?>("UpdatedDate");

                    b.HasKey("Id");

                    b.ToTable("Makes");
                });

            modelBuilder.Entity("CleanApp.Domain.Entities.Mascot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code");

                    b.Property<DateTime?>("CreatedDate");

                    b.Property<int>("MakeId");

                    b.Property<string>("Name");

                    b.Property<DateTime?>("UpdatedDate");

                    b.HasKey("Id");

                    b.HasIndex("MakeId");

                    b.ToTable("Mascots");
                });

            modelBuilder.Entity("CleanApp.Domain.Entities.RentOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ClientId");

                    b.Property<DateTime?>("CreatedDate");

                    b.Property<DateTime>("FromDate");

                    b.Property<DateTime>("PaymentDate");

                    b.Property<decimal>("ShippingPrice");

                    b.Property<DateTime>("ToDate");

                    b.Property<DateTime?>("UpdatedDate");

                    b.HasKey("Id");

                    b.ToTable("RentOrders");
                });

            modelBuilder.Entity("CleanApp.Domain.Entities.RentOrderDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Deposit");

                    b.Property<float>("Discount");

                    b.Property<int>("MascotId");

                    b.Property<short>("Quantity");

                    b.Property<int>("RentOrderId");

                    b.Property<decimal>("UnitPrice");

                    b.HasKey("Id");

                    b.HasIndex("MascotId");

                    b.HasIndex("RentOrderId");

                    b.ToTable("RentOrderDetails");
                });

            modelBuilder.Entity("CleanApp.Domain.Entities.BuyOrderDetails", b =>
                {
                    b.HasOne("CleanApp.Domain.Entities.BuyOrder", "BuyOrder")
                        .WithMany("BuyOrderDetails")
                        .HasForeignKey("BuyOrderId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CleanApp.Domain.Entities.Mascot", "Mascot")
                        .WithMany()
                        .HasForeignKey("MascotId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CleanApp.Domain.Entities.Client", b =>
                {
                    b.HasOne("CleanApp.Domain.Entities.Address", "Address")
                        .WithMany("Clients")
                        .HasForeignKey("AddressId")
                        .HasConstraintName("FK_Clients_Address")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CleanApp.Domain.Entities.Mascot", b =>
                {
                    b.HasOne("CleanApp.Domain.Entities.Make", "Make")
                        .WithMany("Mascots")
                        .HasForeignKey("MakeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CleanApp.Domain.Entities.RentOrderDetails", b =>
                {
                    b.HasOne("CleanApp.Domain.Entities.Mascot", "Mascot")
                        .WithMany()
                        .HasForeignKey("MascotId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CleanApp.Domain.Entities.RentOrder", "RentOrder")
                        .WithMany("RentOrderDetails")
                        .HasForeignKey("RentOrderId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
